pub const COL_TRADUCIDO: &str = "Traducido";
pub const COL_MOTIVO_ELIMINACION: &str = "Motivo_Eliminacion";
pub const COL_HOJA_ORIGEN: &str = "Hoja_origen";
pub const COL_PRECIO2: &str = "Precio2";
pub const COL_OEM: &str = "OEM";
pub const CANTIDAD_CARACTERES_OEM3: usize = 250;
pub const MAX_ROWS_PER_SHEET: usize = 1_000_000;

/// Columnas que el validator genera/usa internamente. Si el archivo de
/// entrada trajera una así, la clasificación quedaría corrupta EN SILENCIO.
pub const COLUMNAS_RESERVADAS: &[&str] = &[
    COL_MOTIVO_ELIMINACION,
    COL_HOJA_ORIGEN,
    "OEM3",
    "_salida",
    "_pid",
    "_prohibida",
    "_motivo_regla",
    "_cond_seg",
    "_preseg",
    "_i",
];

pub fn columnas_reservadas_en<'a>(columnas: impl IntoIterator<Item = &'a str>) -> Vec<String> {
    commerce_core::columnas_reservadas_en(columnas, COLUMNAS_RESERVADAS.iter().copied())
}

/// Nombre de hoja reservado para el reporte (comparación insensible a
/// mayúsculas/espacios): una hoja de ENTRADA llamada así mezclaría sus
/// filas supervivientes dentro del reporte de eliminadas.
pub const HOJA_RESERVADA: &str = "eliminadas";

/// Particiones mínimas del dedup a disco (caso grande).
pub const PARTICIONES_DEDUPLICACION: usize = 8;

/// Umbral del dedup HÍBRIDO: si las filas estimadas caben bajo esto, se
/// deduplica EN MEMORIA (sin disco, más rápido); por encima, se particiona
/// a disco. ~3M es holgado para 8GB; súbelo si hay más RAM disponible.
pub const UMBRAL_RAM_DEDUP: u64 = 3_000_000;

/// Marcas y modelos de coches, camiones, diésel, 4x4 y motos ya excluidos
/// de esta lista (curada): quedan marcas de repuestos, accesorios,
/// herramientas y químicos.
pub const PALABRAS_BASE: &[&str] = &[
    "3M",
    "AASCO",
    "ACC",
    "ACDelco",
    "ACME",
    "ACON",
    "ACP",
    "ACT",
    "ADC",
    "ADFIL",
    "AEM",
    "AFCO Racing",
    "AFE Power",
    "AFN 4x4",
    "AFR",
    "AG-Stump",
    "AIT",
    "AISIN",
    "ALPS",
    "ALS",
    "AMD",
    "AMMCO",
    "AMP Research",
    "ANCO",
    "AP",
    "APDI",
    "APDTY",
    "APG",
    "API",
    "APP",
    "ARP",
    "ART",
    "ASC",
    "ASCO",
    "ATE",
    "ATI",
    "ATL",
    "ATP",
    "ATRO",
    "ATS",
    "AVEC",
    "AWE Tuning",
    "A-MAST",
    "A-Premium",
    "A-R",
    "Accel",
    "AccuAir",
    "AccuTurn",
    "Accufab",
    "Accuform",
    "Accurate",
    "Active Exhaust",
    "Addco",
    "Adler",
    "Advance",
    "Advanced",
    "Advantage",
    "Aerocatch",
    "Aeromotive",
    "Aeroquip",
    "Aftermarket",
    "AiM Sports",
    "Air",
    "AirDog",
    "Airaid",
    "Airtex",
    "Ajusa",
    "Akebono",
    "Akrapovič",
    "AkzoNobel",
    "Alcoa",
    "Allied Nippon",
    "Alpinestars",
    "Altrom",
    "Amalie",
    "Amazing-E",
    "American",
    "Ametek",
    "Amsoil",
    "Anchor",
    "Anderson",
    "Ansa",
    "Anzo",
    "Apex",
    "Arco",
    "Arc-Zone",
    "Arias Pistons",
    "Armature",
    "Armytrix",
    "Arnott",
    "Asahi",
    "Asin",
    "Associated",
    "Asuki",
    "ATD Tools",
    "Auburn Gear",
    "Aurora",
    "Autel",
    "Auto 7",
    "Autocraft",
    "Autogage",
    "Autolite",
    "Autometer",
    "Autopart",
    "Autotecnica",
    "Autotune",
    "Autoventshade",
    "AutoZone",
    "Autronic",
    "Autospecialty",
    "Avery Dennison",
    "B&G",
    "B&I",
    "B&M",
    "B&W",
    "B3",
    "BAK",
    "BBS",
    "BBR",
    "BC Racing",
    "BG",
    "BMR",
    "BTR",
    "BWD",
    "Baer Brakes",
    "Bahco",
    "Baja Designs",
    "Baker",
    "Baldwin",
    "Bando",
    "Barksdale",
    "Bar's Leaks",
    "Barry Grant",
    "Baseline",
    "Basf",
    "Battery Tender",
    "Baum Tools",
    "Be Cool",
    "Beck Arnley",
    "Behr",
    "Bell",
    "Belltech",
    "Bendix",
    "BendPak",
    "Benteler",
    "Berco",
    "Beru",
    "Bestop",
    "Beta",
    "BFGoodrich",
    "Big End",
    "Billet",
    "Billy",
    "Bilstein",
    "Bimecc",
    "Binks",
    "Blackhawk",
    "Blackstone",
    "Blitz",
    "Blue Ox",
    "Blue Streak",
    "BluePrint",
    "Boge",
    "Bondo",
    "Borg",
    "BorgWarner",
    "Borla",
    "Bosch",
    "Bostech",
    "Bovee",
    "Bowa",
    "BP Visco",
    "Brad Penn",
    "BrakeBest",
    "Brakemotive",
    "Braman",
    "Brembo",
    "Bremi",
    "Brian Crower",
    "Bride",
    "Bridgestone",
    "Brock",
    "Brodix",
    "Brunnhoelzl",
    "Brute Force",
    "Bubba Rope",
    "Budge",
    "Bug Deflector",
    "Bully",
    "Bully Dog",
    "Bumper",
    "Bushwacker",
    "Buyers",
    "C&R Racing",
    "CAPA",
    "CAR",
    "CBI",
    "CCI",
    "COMP",
    "COVERCRAFT",
    "CP",
    "CRC",
    "CRP",
    "C-TEK",
    "Cal-Hawk",
    "Cal-Van",
    "Cali",
    "Callies",
    "Calterm",
    "Camco",
    "Canton",
    "Carborundum",
    "Cardone",
    "Carello",
    "Carlson",
    "Car-Pak",
    "CarPro",
    "Carquest",
    "Carr",
    "Carrillo",
    "Carter",
    "Carver",
    "Castrol",
    "Cen-Tec",
    "Center",
    "Centerforce",
    "Centric",
    "Cequent",
    "Certified",
    "Champion",
    "Cibié",
    "Clayton",
    "Clevite",
    "Cloyes",
    "Coast",
    "Coastal",
    "Cobb Tuning",
    "Comec",
    "Cometic",
    "Compressor",
    "Continental",
    "ContiTech",
    "Cooper Tire",
    "Corbeau",
    "Cornwell",
    "Corsa",
    "Corteco",
    "Cosworth",
    "Craftsman",
    "Cragar",
    "Crower",
    "Currie",
    "Curt",
    "Cusco",
    "D2 Racing",
    "DDM Tuning",
    "DEI",
    "DNJ",
    "DOT",
    "DSS",
    "DTS",
    "DashMat",
    "Davies Craig",
    "Dayco",
    "DeatschWerks",
    "Dee Zee",
    "Deka",
    "Delco",
    "Delphi",
    "Denso",
    "Depo",
    "Derale",
    "Devcon",
    "DeWalt",
    "DiabloSport",
    "Diamond Eye",
    "Diode",
    "Dobinsons",
    "Dorman",
    "Draw-Tite",
    "Driveworks",
    "Dunlop",
    "DuPont",
    "Duragloss",
    "Duralast",
    "Dynatronics",
    "Dynojet",
    "EBC",
    "ESOM",
    "EZ LYNK",
    "Earl's",
    "East",
    "Eastwood",
    "Echlin",
    "Edelbrock",
    "Eibach",
    "Electrical",
    "Electromotive",
    "Elf",
    "Elring",
    "Elstock",
    "Energy",
    "Engine Pro",
    "Enginetech",
    "Enkei Wheels",
    "Ensambleje",
    "EverStart",
    "Evercraft",
    "Exedy",
    "Exide",
    "Extang",
    "F&R",
    "FAST",
    "FMP Group",
    "FX Racing",
    "Fab Fours",
    "Fabspeed",
    "Facet",
    "Facom",
    "Falken",
    "FatMat",
    "Febi",
    "Federal-Mogul",
    "Fel-Pro",
    "Ferodo",
    "Ferrea",
    "Fiberall",
    "Fikse Wheels",
    "Firestone",
    "FiTech",
    "Fleece",
    "Flex-A-Lite",
    "Flo-Pro",
    "Flowmaster",
    "Flowtech",
    "Fluidampr",
    "Forgeline",
    "Forgestar",
    "Fortune Auto",
    "Four Seasons",
    "Fox",
    "Foxwell",
    "Fram",
    "Fuel Offroad",
    "Fuel Safe",
    "Fusor",
    "G2",
    "GEDORE",
    "G-FORCE",
    "GMB",
    "GPD",
    "GRP",
    "GSP",
    "GTechniq",
    "Gabriel",
    "Garrett",
    "Gates",
    "GearWrench",
    "General Tire",
    "GenRight",
    "Genérica",
    "Geomet",
    "Girling",
    "Global West",
    "Godspeed",
    "Goetze",
    "Goodson",
    "Goodyear",
    "Granatelli",
    "GReddy",
    "Green",
    "Griffin",
    "Griot's",
    "Grote",
    "Gumout",
    "Gunk",
    "H&R Springs",
    "HKS",
    "Haltech",
    "Hankook",
    "Hardrace",
    "Hawk",
    "Hayden",
    "Hazet",
    "Hella",
    "Hellwig",
    "Hengst",
    "Herko",
    "Hitachi",
    "Holley",
    "Hondata",
    "Honeywell",
    "Hooker",
    "Hoosier",
    "Hopkins",
    "Hot",
    "Hotchkis",
    "House",
    "Howards",
    "HRE Wheels",
    "Hughes",
    "Hunter",
    "Hurst",
    "Husky",
    "Hypertech",
    "IPC",
    "ISR",
    "ITM",
    "Icon",
    "Import",
    "Injection",
    "Injen",
    "Inland",
    "Innova",
    "Intercomp",
    "Intermotor",
    "Interstate",
    "Isky",
    "Ishino",
    "J&N",
    "J.B. Weld",
    "JBA Exhaust",
    "JE",
    "JKS",
    "JRi Shocks",
    "Jegs",
    "Jesel",
    "Jet Chips",
    "John Bean",
    "Jurid",
    "K&N",
    "K&P",
    "K&W Products",
    "KC HiLiTES",
    "KMC Wheels",
    "KTuner",
    "KW s",
    "KYB",
    "Kirkey",
    "Knipex",
    "Kobalt Tools",
    "Koken",
    "Kolbenschmidt",
    "Koni",
    "Konig Wheels",
    "Koso",
    "Koyorad",
    "Ksport USA",
    "Kumho",
    "Kwik-Way",
    "LABLT",
    "Labwork",
    "Lakewood",
    "Lares",
    "Launch Tech",
    "Lazer Lamps",
    "Lemförder",
    "Link",
    "Liqui Moly",
    "Lisle",
    "Lloyd Mats",
    "Lock-Right",
    "Loctite",
    "Longacre",
    "Luber-Finer",
    "Lucas",
    "Lunati",
    "MAS",
    "MBRP Exhaust",
    "MEI",
    "MSD",
    "Mac Tools",
    "Mag-Hytec",
    "MagnaFlow",
    "Magnecor",
    "Mahle",
    "Maier",
    "Makita",
    "Mallory",
    "Manley",
    "Mann-Filter",
    "Master",
    "MasterPro",
    "Matco Tools",
    "Maxxis",
    "MaXpeedingrods",
    "Megan Racing",
    "Meguiar's",
    "Melling",
    "Method",
    "Mevotech",
    "Michelin",
    "Mickey",
    "Midtronics",
    "Milwaukee",
    "Mintex",
    "Mishimoto",
    "Mitsuboshi",
    "Mobil 1",
    "Mocal",
    "Molnar",
    "Monroe",
    "Monster",
    "Moog",
    "Mopar",
    "Morimoto",
    "Moroso",
    "Moser",
    "Motec",
    "Motegi",
    "Motobatt",
    "Motorad",
    "Motorcraft",
    "Motul",
    "Mr. Gasket",
    "Murray",
    "MyLaps",
    "Mystik",
    "NAPA",
    "NGK",
    "NOCO",
    "NPK",
    "NX",
    "Narva",
    "Neway",
    "Nexen Tire",
    "Nissens",
    "Nitto",
    "Noico",
    "Norco",
    "Nos",
    "Novus",
    "OEG",
    "OEMTOOLS",
    "OS Giken",
    "OTC Tools",
    "OZ Racing",
    "Odyssey",
    "Oliver",
    "Omega",
    "OptiMate",
    "Optima",
    "Optimum",
    "Oracle",
    "O'Reilly",
    "Osram",
    "Ox Locker",
    "PAC",
    "PARTS",
    "PBM",
    "PBR",
    "PML",
    "POR-15",
    "PPE",
    "PPG",
    "PST",
    "Pagid",
    "Painless",
    "Parker",
    "Parts Plus",
    "PartsMaster",
    "Pauter",
    "Pennzoil",
    "Penske",
    "Pep Boys",
    "Performance",
    "Permatex",
    "Pertronix",
    "Peterson",
    "Philips",
    "Piaa",
    "Pierburg",
    "Pirelli",
    "Pitman",
    "Pittsburgh",
    "Plexus",
    "Poison",
    "Poorboy's",
    "Power",
    "Power Stop",
    "Power Trax",
    "Powerbuilt",
    "Precision",
    "Prestolite",
    "Prestone",
    "Pro Comp",
    "Proform",
    "Products",
    "Proliance",
    "Prothane",
    "Proto",
    "Purolator",
    "Putco",
    "QA1",
    "Quaife",
    "Quaker State",
    "Quality",
    "Quick",
    "QuickJack",
    "QuickSteer",
    "Quinn",
    "RAC",
    "RYC",
    "Raceline",
    "Racepak",
    "Racor",
    "Rain-X",
    "Ranch Hand",
    "Rancho",
    "Rare",
    "Raybestos",
    "Ready-Aire",
    "Recaro",
    "Red",
    "Red Dot",
    "Reese",
    "Rein",
    "Remanufacturado",
    "Remus",
    "Remy",
    "Retrax",
    "RevMax",
    "Rhino-Rack",
    "RideTech",
    "Ridgid",
    "Rigid",
    "Ring",
    "Riscone",
    "Rock Krawler",
    "Rockwell",
    "Rotary Lift",
    "Rotiform",
    "Rotor Master",
    "Rottler",
    "Rough Country",
    "Royal Purple",
    "Russell",
    "Ryobi",
    "Sachs",
    "Safety-Kleen",
    "SCT",
    "SEM",
    "SFI",
    "SKF",
    "SPAL",
    "SPC",
    "SPEC Clutch",
    "SPL Parts",
    "SSI",
    "STP",
    "Scat",
    "Schaeffler",
    "Schumacher",
    "Second",
    "Serdi",
    "Setrab",
    "Shell",
    "Sherwin-Williams",
    "Silens",
    "Simpson",
    "Smith",
    "Smittybilt",
    "Snap-on",
    "Snoopy",
    "Solar",
    "Sonax",
    "Sparco",
    "Spectra",
    "Spectre",
    "Speedmaster",
    "Speedtech",
    "Speedway",
    "Sprocket",
    "Spyder Auto",
    "Stahlwille",
    "Sta-Lube",
    "Standard",
    "Stanley",
    "Stant",
    "Status",
    "Stewart",
    "StopTech",
    "Strange",
    "Sumitomo",
    "Summit",
    "Sun",
    "Sunbelt",
    "SunCoast",
    "Sunex Tools",
    "Sunnen",
    "Sunstar",
    "Super Start",
    "Superchips",
    "Superlift",
    "SuperPro",
    "SuperSprings",
    "Supersprint",
    "Supersprox",
    "Supertech",
    "Superior",
    "SureBilt",
    "SureStop",
    "Swepco",
    "Sylvania",
    "T&D Machine",
    "TCI Auto",
    "TRQ",
    "TRW",
    "TSW",
    "TYC",
    "Taylor",
    "Techron",
    "Tech-Zone",
    "Tein",
    "Tekonsha",
    "Teng Tools",
    "Tenneco/DRiV",
    "TeraFlex",
    "Textar",
    "Thermo-Tec",
    "Thinkcar",
    "Tokico",
    "Tom",
    "Tomei",
    "Tonichi",
    "Topdon",
    "Torklift",
    "TotalEnergies",
    "Toyo",
    "TPR",
    "Trail-Gear",
    "Transtar",
    "Traveler",
    "Trend",
    "Trick",
    "Trico",
    "TruXedo",
    "Turbonetics",
    "UAC",
    "UFI Filters",
    "U-POL",
    "URO",
    "USAG",
    "UnderCover",
    "Unichip",
    "Universal Air",
    "VIAIR",
    "Valeo",
    "Valuecraft",
    "Valvoline",
    "Varios Modelos",
    "Varta",
    "VDO",
    "Vernet",
    "Victor Reinz",
    "Vision Wheel",
    "Vision X",
    "Volk Racing",
    "Vortech",
    "Vossen",
    "WAI Global",
    "WARN",
    "Wagner",
    "Walbro",
    "Walker",
    "Wearever",
    "Weather",
    "WeatherTech",
    "Weiand",
    "Weld Racing",
    "Wells",
    "Wera Tools",
    "Westin",
    "Whipple",
    "Whiteline",
    "Wiha Tools",
    "Wilwood",
    "WiperTechnologies",
    "Wiseco",
    "Wix",
    "Wolfgang",
    "World",
    "Worldpac",
    "XD Wheels",
    "XenonDepot",
    "Yokohama",
    "ZF",
    "Zerex",
    "Zex",
    "aFe",
    "Öhlins",
];

/// Palabras críticas cuya variante upper/lower/title se añade explícitamente
/// (deben coincidir sin importar mayúsculas, con independencia de la forma
/// ya presente en [`PALABRAS_BASE`]).
pub const PALABRAS_CRITICAS: &[&str] = &["Mopar", "Motorcraft", "ACDelco"];

/// Palabras que deben filtrar la fila COMPLETA (marca/modelo prohibido).
pub const PALABRAS_PROHIBIDAS: &[&str] = &[
    // Tecnología y General
    "Android",
    "CarPlay",
    "Radio",
    "Original",
    "Apple",
    "Wireless",
    "Smartphone",
    "MirrorLink",
    "Bluetooth",
    "Wi-Fi",
    "Ecosystem",
    "Cloud",
    "Touchscreen",
    "Display",
    "GPS",
    "Receiver",
    "Navigation",
    "Maps",
    "Google",
    "Waze",
    "Siri",
    "Firmware",
    "Universal",
    "Cummins",
    "Scan",
    "Genuino",
    "Genuine",
    "emblema",
    "emblem",
    "logo",
    // Marcas
    "Hyundai",
    "Kia",
    "John Deere",
    // Modelos Hyundai / Kia
    "i10",
    "i20",
    "i30",
    "i40",
    "Accent",
    "Verna",
    "Elantra",
    "Avante",
    "Sonata",
    "Grandeur",
    "Azera",
    "Ioniq",
    "Ioniq 5",
    "Ioniq 6",
    "Ioniq 9",
    "Veloster",
    "HB20",
    "Casper",
    "Bayon",
    "Venue",
    "Venues",
    "Exter",
    "Alcazar",
    "Kona",
    "Creta",
    "ix25",
    "Tucson",
    "Santa Fe",
    "Palisade",
    "Nexo",
    "Mufasa",
    "Santa Cruz",
    "Staria",
    "H-1",
    "Starex",
    "Picanto",
    "Rio",
    "K2",
    "K3",
    "K4",
    "K5",
    "K8",
    "K9",
    "K900",
    "Quoris",
    "Pegas",
    "Ray",
    "Ceed",
    "Stinger",
    "Stonic",
    "Sonet",
    "Seltos",
    "Niro",
    "Sportage",
    "Sorento",
    "Mohave",
    "Borrego",
    "Telluride",
    "XCeed",
    "Soul",
    "EV3",
    "EV4",
    "EV5",
    "EV6",
    "EV9",
    "Carnival",
    "Sedona",
    "Carens",
    "Tasman",
    // Modelos John Deere
    "1023E",
    "1025R",
    "2025R",
    "2032R",
    "2038R",
    "3025D",
    "3025E",
    "3032E",
    "3033R",
    "3035D",
    "3038E",
    "3039R",
    "3043D",
    "3046R",
    "4044M",
    "4044R",
    "4052M",
    "4052R",
    "4066M",
    "4066R",
    "5045E",
    "5050E",
    "5055E",
    "5060E",
    "5065E",
    "5067E",
    "5075E",
    "5075M",
    "5090M",
    "5090EL",
    "5100M",
    "5100ML",
    "5115M",
    "5125M",
    "5100R",
    "5115R",
    "5125R",
    "6105E",
    "6110M",
    "6110R",
    "6120M",
    "6120R",
    "6130M",
    "6130R",
    "6135E",
    "6140M",
    "6145M",
    "6145R",
    "6155M",
    "6155R",
    "6155MH",
    "6175M",
    "6175R",
    "6195M",
    "6195R",
    "6210R",
    "6215R",
    "6230R",
    "6250R",
    "7R 210",
    "7R 230",
    "7R 250",
    "7R 270",
    "7R 290",
    "7R 310",
    "7R 330",
    "7R 350",
    "8R 230",
    "8R 250",
    "8R 280",
    "8R 310",
    "8R 340",
    "8R 370",
    "8R 410",
    "8RT 310",
    "8RT 340",
    "8RT 370",
    "8RT 410",
    "8RX 310",
    "8RX 340",
    "8RX 370",
    "8RX 410",
    "9R 390",
    "9R 440",
    "9R 490",
    "9R 540",
    "9R 590",
    "9R 640",
    "9RT 470",
    "9RT 520",
    "9RT 570",
    "9RX 490",
    "9RX 540",
    "9RX 590",
    "9RX 640",
    "9RX 710",
    "9RX 770",
    "9RX 830",
    "S760",
    "S770",
    "S780",
    "S790",
    "X9 1000",
    "X9 1100",
    "T550",
    "T560",
    "T660",
    "T670",
    "W540",
    "W550",
    "W650",
    "310L",
    "310SL",
    "315SL",
    "325G",
    "331G",
    "333G",
    "410L",
    "710L",
    "17G",
    "26G",
    "30G",
    "35G",
    "50G",
    "60G",
    "75G",
    "85G",
    "130G",
    "160G",
    "180G",
    "210G",
    "245G",
    "250G",
    "300G",
    "345G",
    "350G",
    "380G",
    "470G",
    "670G",
    "870G",
    "450K",
    "550K",
    "650K",
    "700L",
    "750L",
    "850L",
    "950K",
    "1050K",
    "204L",
    "304L",
    "324L",
    "344L",
    "444G",
    "524P",
    "544P",
    "624P",
    "644P",
    "724P",
    "744P",
    "824P",
    "844P",
    "944K",
    "HPX615E",
    "HPX815E",
    "TH 6X4",
    "TX 4X2",
    "TS 4X2",
    "XUV560E",
    "XUV590M",
    "XUV825M",
    "XUV835M",
    "XUV835R",
    "XUV855M",
    "XUV865M",
    "XUV865R",
    "8100",
    "8200",
    "8300",
    "8400",
    "8500",
    "8600",
    "9500",
    "9600",
    "9700",
    "9800",
    "9900",
    "F441R",
    "V451G",
    "V451M",
    "V461M",
    "V461R",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detecta_columnas_reservadas() {
        assert_eq!(
            columnas_reservadas_en(["Traducido", "OEM3"]),
            vec!["OEM3".to_string()]
        );
        assert!(columnas_reservadas_en(["Traducido"]).is_empty());
    }
}
