[package]
name = "etl_tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
aho-corasick = "1.1.4"
app_shell = { workspace = true }
commerce_core = { workspace = true }
indicatif = { workspace = true }
polars = { workspace = true, features = ["concat_str"] }
regex = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rust_xlsxwriter = { workspace = true }
tempfile = { workspace = true }
